### ISSUE TITLE
Unresolved reference 'Crypto' and Unresolved reference 'AES'

### ISSUE THREAD

**Issue by deman2660** [henry-richard7/Browser-password-stealer#1]
When trying to run it i get the errors Unresolved reference 'AES' and Unresolved reference 'Crypto' 
 
![image](https://user-images.githubusercontent.com/73039800/102287265-fe759c00-3f31-11eb-883e-5aa7210dc0aa.png)
can i get some help with this?

**Comment by henry-richard7** [comment]
Hi,
 Please install pycrypto using "**pip install pycrypto**"

**Comment by deman2660** [comment]
I have tried that but i get this error [https://pastebin.com/226JMgck](url) is there a way to fix it?

**Comment by henry-richard7** [comment]
are you trying to use pyinstaller?

**Comment by deman2660** [comment]
I am not using pyinstaller i am using pip install and cant get it to install

**Comment by henry-richard7** [comment]
please try these 
pip uninstall pycrypto
pip install pycryptodome
