### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

### ISSUE THREAD

**Issue by diehard88** [henry-richard7/Browser-password-stealer#14]
![Screenshot_20230810-224913_Termux](https://github.com/henry-richard7/Browser-password-stealer/assets/25366502/0ba79c62-16d9-4e6f-a9c8-49f7e6ae8598)

`# pip -V

pip 23.2 from /usr/lib/python3/dist-packages/pip (python 3.11)`

**Comment by TheRealBeelzebub666** [comment]
Here is The FIX !
pip3 install -r requirements

**Comment by diehard88** [comment]
> 

are you sure?

**Comment by TheRealBeelzebub666** [comment]
> > 
> 
> are you sure?

Yes

**Comment by diehard88** [comment]
> > > > 
> > > 
> > > 
> > > are you sure?
> > 
> > 
> > Yes
> 
> did you test your 'fix' to be so confident?

nope...

**Comment by hahahahacker2009** [comment]
that setup.py is having problem: it print "text" instead of print("text"). Upgrade to the latest version of package should fix (if there are a merged patch)

**Comment by diehard88** [comment]
> 

upgrade which specific package?

**Comment by diehard88** [comment]
> that setup.py is having problem: it print "text" instead of print("text"). Upgrade to the latest version of package should fix (if there are a merged patch)

upgrade which specific package?

**Comment by hahahahacker2009** [comment]
> > that setup.py is having problem: it print "text" instead of print("text"). Upgrade to the latest version of package should fix (if there are a merged patch)
> 
> upgrade which specific package?

The package which contain error: pypiwin32
