### ISSUE TITLE
there is no config.ini file

### ISSUE THREAD

**Issue by jamiekarvans** [henry-richard7/Browser-password-stealer#8]

**Comment by henry-richard7** [comment]
This script doesn't use a config.ini file. You can directly run the script.

**Comment by jamiekarvans** [comment]
But it says in the description, to put the email password in config.ini
Does it still sends the data to Gmail?

**Comment by henry-richard7** [comment]
I have made a mistake in the description I have changed it.

No it does not send the data in mail. It stores the data in a local folder. Check the updated description.

**Comment by pierre669reborn** [comment]
@henry-richard7 Hey please answer the Issue I opened weeks ago about the browser cookies
